#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GestionnaireDeLivreMobile.Resource", IsApplication=true)]

namespace GestionnaireDeLivreMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int liste_code = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int boutonAjouterLivre = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int boutonChercher = 2131099653;
			
			// aapt resource value: 0x7f060018
			public const int boutonCreerCompte = 2131099672;
			
			// aapt resource value: 0x7f060010
			public const int boutonCreerCompteEtudiant = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int boutonCreerCompteGestionnaire = 2131099665;
			
			// aapt resource value: 0x7f060003
			public const int boutonDeconexion = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int boutonSeConnecter = 2131099661;
			
			// aapt resource value: 0x7f06001c
			public const int champAdresseCooperative = 2131099676;
			
			// aapt resource value: 0x7f060007
			public const int champCode = 2131099655;
			
			// aapt resource value: 0x7f060017
			public const int champConfirmationMotDePasse = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int champCourriel = 2131099667;
			
			// aapt resource value: 0x7f06000a
			public const int champIdentifiant = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int champMotDePasse = 2131099660;
			
			// aapt resource value: 0x7f06001a
			public const int champNomCooperative = 2131099674;
			
			// aapt resource value: 0x7f060015
			public const int champTelephone = 2131099669;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int relativeLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int spinner = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int textView1 = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int texteAdresseCooperative = 2131099675;
			
			// aapt resource value: 0x7f060016
			public const int texteConfirmationMotDePasse = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int texteCourriel = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int texteErreurLogin = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int texteIdentifiant = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int texteInfoLivre = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int texteMotDePasse = 2131099659;
			
			// aapt resource value: 0x7f060019
			public const int texteNomCoopreative = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int texteTelephone = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int texteValeurLivre = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int PageAccueil = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PageAjoutLivre = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PageConnexion = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PageCreationCompteEtudiant = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PageCreationCompteGestionnaire = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int demande_type_code = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
