/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-09-24 12:41:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Accueil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./CommandJSPImport/Header.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mainmenu-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"navbar-collapse collapse\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav\">\r\n");
      out.write("                        <li class=\"active\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"shop.html\">Shop page</a></li>\r\n");
      out.write("                        <li><a href=\"single-product.html\">Single product</a></li>\r\n");
      out.write("                        <li><a href=\"cart.html\">Cart</a></li>\r\n");
      out.write("                        <li><a href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Category</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Others</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End mainmenu area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"slider-area\">\r\n");
      out.write("        \t<!-- Slider -->\r\n");
      out.write("\t\t\t<div class=\"block-slider block-slider4\">\r\n");
      out.write("\t\t\t\t<ul class=\"\" id=\"bxslider-home4\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/h4-slide.png\" alt=\"Slide\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"caption title\">\r\n");
      out.write("\t\t\t\t\t\t\t\tiPhone <span class=\"primary\">6 <strong>Plus</strong></span>\r\n");
      out.write("\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"caption subtitle\">Dual SIM</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"caption button-radius\" href=\"#\"><span class=\"icon\"></span>Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"img/h4-slide2.png\" alt=\"Slide\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"caption title\">\r\n");
      out.write("\t\t\t\t\t\t\t\tby one, get one <span class=\"primary\">50% <strong>off</strong></span>\r\n");
      out.write("\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"caption subtitle\">school supplies & backpacks.*</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"caption button-radius\" href=\"#\"><span class=\"icon\"></span>Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"img/h4-slide3.png\" alt=\"Slide\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"caption title\">\r\n");
      out.write("\t\t\t\t\t\t\t\tApple <span class=\"primary\">Store <strong>Ipod</strong></span>\r\n");
      out.write("\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"caption subtitle\">Select Item</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"caption button-radius\" href=\"#\"><span class=\"icon\"></span>Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"img/h4-slide4.png\" alt=\"Slide\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption-group\">\r\n");
      out.write("\t\t\t\t\t\t  <h2 class=\"caption title\">\r\n");
      out.write("\t\t\t\t\t\t\t\tApple <span class=\"primary\">Store <strong>Ipod</strong></span>\r\n");
      out.write("\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"caption subtitle\">& Phone</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"caption button-radius\" href=\"#\"><span class=\"icon\"></span>Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- ./Slider -->\r\n");
      out.write("    </div> <!-- End slider area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"promo-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"single-promo promo1\">\r\n");
      out.write("                        <i class=\"fa fa-refresh\"></i>\r\n");
      out.write("                        <p>30 Days return</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"single-promo promo2\">\r\n");
      out.write("                        <i class=\"fa fa-truck\"></i>\r\n");
      out.write("                        <p>Free shipping</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"single-promo promo3\">\r\n");
      out.write("                        <i class=\"fa fa-lock\"></i>\r\n");
      out.write("                        <p>Secure payments</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"single-promo promo4\">\r\n");
      out.write("                        <i class=\"fa fa-gift\"></i>\r\n");
      out.write("                        <p>New products</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End promo area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"maincontent-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"latest-product\">\r\n");
      out.write("                        <h2 class=\"section-title\">Latest Products</h2>\r\n");
      out.write("                        <div class=\"product-carousel\">\r\n");
      out.write("                            <div class=\"single-product\">\r\n");
      out.write("                                <div class=\"product-f-image\">\r\n");
      out.write("                                    <img src=\"img/product-1.jpg\" alt=\"\">\r\n");
      out.write("                                    <div class=\"product-hover\">\r\n");
      out.write("                                        <a href=\"#\" class=\"add-to-cart-link\"><i class=\"fa fa-shopping-cart\"></i> Add to cart</a>\r\n");
      out.write("                                        <a href=\"single-product.html\" class=\"view-details-link\"><i class=\"fa fa-link\"></i> See details</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <h2><a href=\"single-product.html\">Samsung Galaxy s5- 2015</a></h2>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"product-carousel-price\">\r\n");
      out.write("                                    <ins>$700.00</ins> <del>$100.00</del>\r\n");
      out.write("                                </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"single-product\">\r\n");
      out.write("                                <div class=\"product-f-image\">\r\n");
      out.write("                                    <img src=\"img/product-2.jpg\" alt=\"\">\r\n");
      out.write("                                    <div class=\"product-hover\">\r\n");
      out.write("                                        <a href=\"#\" class=\"add-to-cart-link\"><i class=\"fa fa-shopping-cart\"></i> Add to cart</a>\r\n");
      out.write("                                        <a href=\"single-product.html\" class=\"view-details-link\"><i class=\"fa fa-link\"></i> See details</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <h2>Nokia Lumia 1320</h2>\r\n");
      out.write("                                <div class=\"product-carousel-price\">\r\n");
      out.write("                                    <ins>$899.00</ins> <del>$999.00</del>\r\n");
      out.write("                                </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"single-product\">\r\n");
      out.write("                                <div class=\"product-f-image\">\r\n");
      out.write("                                    <img src=\"img/product-3.jpg\" alt=\"\">\r\n");
      out.write("                                    <div class=\"product-hover\">\r\n");
      out.write("                                        <a href=\"#\" class=\"add-to-cart-link\"><i class=\"fa fa-shopping-cart\"></i> Add to cart</a>\r\n");
      out.write("                                        <a href=\"single-product.html\" class=\"view-details-link\"><i class=\"fa fa-link\"></i> See details</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <h2>LG Leon 2015</h2>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"product-carousel-price\">\r\n");
      out.write("                                    <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                                </div>                                 \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"single-product\">\r\n");
      out.write("                                <div class=\"product-f-image\">\r\n");
      out.write("                                    <img src=\"img/product-4.jpg\" alt=\"\">\r\n");
      out.write("                                    <div class=\"product-hover\">\r\n");
      out.write("                                        <a href=\"#\" class=\"add-to-cart-link\"><i class=\"fa fa-shopping-cart\"></i> Add to cart</a>\r\n");
      out.write("                                        <a href=\"single-product.html\" class=\"view-details-link\"><i class=\"fa fa-link\"></i> See details</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <h2><a href=\"single-product.html\">Sony microsoft</a></h2>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"product-carousel-price\">\r\n");
      out.write("                                    <ins>$200.00</ins> <del>$225.00</del>\r\n");
      out.write("                                </div>                            \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"single-product\">\r\n");
      out.write("                                <div class=\"product-f-image\">\r\n");
      out.write("                                    <img src=\"img/product-5.jpg\" alt=\"\">\r\n");
      out.write("                                    <div class=\"product-hover\">\r\n");
      out.write("                                        <a href=\"#\" class=\"add-to-cart-link\"><i class=\"fa fa-shopping-cart\"></i> Add to cart</a>\r\n");
      out.write("                                        <a href=\"single-product.html\" class=\"view-details-link\"><i class=\"fa fa-link\"></i> See details</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <h2>iPhone 6</h2>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"product-carousel-price\">\r\n");
      out.write("                                    <ins>$1200.00</ins> <del>$1355.00</del>\r\n");
      out.write("                                </div>                                 \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"single-product\">\r\n");
      out.write("                                <div class=\"product-f-image\">\r\n");
      out.write("                                    <img src=\"img/product-6.jpg\" alt=\"\">\r\n");
      out.write("                                    <div class=\"product-hover\">\r\n");
      out.write("                                        <a href=\"#\" class=\"add-to-cart-link\"><i class=\"fa fa-shopping-cart\"></i> Add to cart</a>\r\n");
      out.write("                                        <a href=\"single-product.html\" class=\"view-details-link\"><i class=\"fa fa-link\"></i> See details</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <h2><a href=\"single-product.html\">Samsung gallaxy note 4</a></h2>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"product-carousel-price\">\r\n");
      out.write("                                    <ins>$400.00</ins>\r\n");
      out.write("                                </div>                            \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End main content area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"brands-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"brand-wrapper\">\r\n");
      out.write("                        <div class=\"brand-list\">\r\n");
      out.write("                            <img src=\"img/brand1.png\" alt=\"\">\r\n");
      out.write("                            <img src=\"img/brand2.png\" alt=\"\">\r\n");
      out.write("                            <img src=\"img/brand3.png\" alt=\"\">\r\n");
      out.write("                            <img src=\"img/brand4.png\" alt=\"\">\r\n");
      out.write("                            <img src=\"img/brand5.png\" alt=\"\">\r\n");
      out.write("                            <img src=\"img/brand6.png\" alt=\"\">\r\n");
      out.write("                            <img src=\"img/brand1.png\" alt=\"\">\r\n");
      out.write("                            <img src=\"img/brand2.png\" alt=\"\">                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End brands area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"product-widget-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"single-product-widget\">\r\n");
      out.write("                        <h2 class=\"product-wid-title\">Top Sellers</h2>\r\n");
      out.write("                        <a href=\"\" class=\"wid-view-more\">View All</a>\r\n");
      out.write("                        <div class=\"single-wid-product\">\r\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-1.jpg\" alt=\"\" class=\"product-thumb\"></a>\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-wid-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product-wid-price\">\r\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-wid-product\">\r\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-2.jpg\" alt=\"\" class=\"product-thumb\"></a>\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Apple new mac book 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-wid-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product-wid-price\">\r\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-wid-product\">\r\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-3.jpg\" alt=\"\" class=\"product-thumb\"></a>\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Apple new i phone 6</a></h2>\r\n");
      out.write("                            <div class=\"product-wid-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product-wid-price\">\r\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"single-product-widget\">\r\n");
      out.write("                        <h2 class=\"product-wid-title\">Recently Viewed</h2>\r\n");
      out.write("                        <a href=\"#\" class=\"wid-view-more\">View All</a>\r\n");
      out.write("                        <div class=\"single-wid-product\">\r\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-4.jpg\" alt=\"\" class=\"product-thumb\"></a>\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony playstation microsoft</a></h2>\r\n");
      out.write("                            <div class=\"product-wid-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product-wid-price\">\r\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-wid-product\">\r\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-1.jpg\" alt=\"\" class=\"product-thumb\"></a>\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart Air Condtion</a></h2>\r\n");
      out.write("                            <div class=\"product-wid-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product-wid-price\">\r\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-wid-product\">\r\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-2.jpg\" alt=\"\" class=\"product-thumb\"></a>\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Samsung gallaxy note 4</a></h2>\r\n");
      out.write("                            <div class=\"product-wid-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product-wid-price\">\r\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"single-product-widget\">\r\n");
      out.write("                        <h2 class=\"product-wid-title\">Top New</h2>\r\n");
      out.write("                        <a href=\"#\" class=\"wid-view-more\">View All</a>\r\n");
      out.write("                        <div class=\"single-wid-product\">\r\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-3.jpg\" alt=\"\" class=\"product-thumb\"></a>\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Apple new i phone 6</a></h2>\r\n");
      out.write("                            <div class=\"product-wid-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product-wid-price\">\r\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-wid-product\">\r\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-4.jpg\" alt=\"\" class=\"product-thumb\"></a>\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Samsung gallaxy note 4</a></h2>\r\n");
      out.write("                            <div class=\"product-wid-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product-wid-price\">\r\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-wid-product\">\r\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-1.jpg\" alt=\"\" class=\"product-thumb\"></a>\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony playstation microsoft</a></h2>\r\n");
      out.write("                            <div class=\"product-wid-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product-wid-price\">\r\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End product widget area -->\r\n");
      out.write("    \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./CommandJSPImport/Footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
