#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GestionnaireDeLivreMobile.Resource", IsApplication=true)]

namespace GestionnaireDeLivreMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::GestionnaireDeLivreMobile.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::GestionnaireDeLivreMobile.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::GestionnaireDeLivreMobile.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int liste_code = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int liste_etats = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int liste_transactions = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int boutonAjouterLivre = 2131165195;
			
			// aapt resource value: 0x7f070017
			public const int boutonChercher = 2131165207;
			
			// aapt resource value: 0x7f070032
			public const int boutonCreerCompte = 2131165234;
			
			// aapt resource value: 0x7f07002a
			public const int boutonCreerCompteEtudiant = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int boutonCreerCompteGestionnaire = 2131165227;
			
			// aapt resource value: 0x7f07000c
			public const int boutonDeconexion = 2131165196;
			
			// aapt resource value: 0x7f070028
			public const int boutonSeConnecter = 2131165224;
			
			// aapt resource value: 0x7f070023
			public const int bouttonScanner = 2131165219;
			
			// aapt resource value: 0x7f070007
			public const int buttonFragment = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int buttonGenerate = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int buttonScanContinuous = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int buttonScanCustomView = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int buttonScanDefaultView = 2131165188;
			
			// aapt resource value: 0x7f070039
			public const int buttonZxingFlash = 2131165241;
			
			// aapt resource value: 0x7f070036
			public const int champAdresseCooperative = 2131165238;
			
			// aapt resource value: 0x7f07001b
			public const int champAuteur = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int champCathegorie = 2131165214;
			
			// aapt resource value: 0x7f070019
			public const int champCode = 2131165209;
			
			// aapt resource value: 0x7f070031
			public const int champConfirmationMotDePasse = 2131165233;
			
			// aapt resource value: 0x7f07002d
			public const int champCourriel = 2131165229;
			
			// aapt resource value: 0x7f07001c
			public const int champEditeur = 2131165212;
			
			// aapt resource value: 0x7f070025
			public const int champIdentifiant = 2131165221;
			
			// aapt resource value: 0x7f07001d
			public const int champLangue = 2131165213;
			
			// aapt resource value: 0x7f070027
			public const int champMotDePasse = 2131165223;
			
			// aapt resource value: 0x7f070022
			public const int champNbPages = 2131165218;
			
			// aapt resource value: 0x7f070034
			public const int champNomCooperative = 2131165236;
			
			// aapt resource value: 0x7f070021
			public const int champPrix = 2131165217;
			
			// aapt resource value: 0x7f07002f
			public const int champTelephone = 2131165231;
			
			// aapt resource value: 0x7f07001a
			public const int champTitre = 2131165210;
			
			// aapt resource value: 0x7f07003a
			public const int contentFrame = 2131165242;
			
			// aapt resource value: 0x7f070001
			public const int fragment_container = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int imageBarcode = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout1 = 2131165193;
			
			// aapt resource value: 0x7f070037
			public const int linearLayout2 = 2131165239;
			
			// aapt resource value: 0x7f070016
			public const int relativeLayout1 = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int spinnerCode = 2131165208;
			
			// aapt resource value: 0x7f07001f
			public const int spinnerConditionLivre = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int spinnerTypeTransaction = 2131165216;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			// aapt resource value: 0x7f070038
			public const int textView3 = 2131165240;
			
			// aapt resource value: 0x7f070035
			public const int texteAdresseCooperative = 2131165237;
			
			// aapt resource value: 0x7f07000e
			public const int texteAuteur = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int texteCategorie = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int texteCondition = 2131165202;
			
			// aapt resource value: 0x7f070030
			public const int texteConfirmationMotDePasse = 2131165232;
			
			// aapt resource value: 0x7f070015
			public const int texteCoopérative = 2131165205;
			
			// aapt resource value: 0x7f07002c
			public const int texteCourriel = 2131165228;
			
			// aapt resource value: 0x7f07000f
			public const int texteEditeur = 2131165199;
			
			// aapt resource value: 0x7f070029
			public const int texteErreurLogin = 2131165225;
			
			// aapt resource value: 0x7f070024
			public const int texteIdentifiant = 2131165220;
			
			// aapt resource value: 0x7f070010
			public const int texteLangue = 2131165200;
			
			// aapt resource value: 0x7f070026
			public const int texteMotDePasse = 2131165222;
			
			// aapt resource value: 0x7f070033
			public const int texteNomCoopreative = 2131165235;
			
			// aapt resource value: 0x7f070014
			public const int textePrix = 2131165204;
			
			// aapt resource value: 0x7f07002e
			public const int texteTelephone = 2131165230;
			
			// aapt resource value: 0x7f07000d
			public const int texteTitre = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int texteTypeTransaction = 2131165203;
			
			// aapt resource value: 0x7f07000a
			public const int texteValeurLivre = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FragmentActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ImageActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PageAccueil = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PageAfficherLivre = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PageAjoutLivre = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PageConnexion = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PageCreationCompteEtudiant = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PageCreationCompteGestionnaire = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ZxingOverlay = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscanneractivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int zxingscannerfragmentlayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int demande_condition_livre = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int demande_type_code = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int demande_type_transaction = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
