#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GestionnaireDeLivre.Resource", IsApplication=true)]

namespace GestionnaireDeLivreMobile.Resources
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000c
			public const int boutonCreerCompte = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int boutonSeConnecter = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int champConfirmationMotDePasse = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int champCourriel = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int champIdentifiant = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int champMotDePasse = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int champTelephone = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int texteConfirmationMotDePasse = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int texteCourriel = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int texteErreurLogin = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int texteIdentifiant = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int texteMotDePasse = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int texteTelephone = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int PageConnection = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PageCreationCompteEtudiant = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
